#!/bin/bash
#Script menu
echo -e "HY KUMPULSEMUT MENU PERINTAH"
echo -e "speedtest --share : untuk cek speed vps"
echo -e "mem : untuk melihat pemakaian ram"
echo -e "checkvirus : untuk scan virus / malware"
echo -e "bench : untuk melihat performa vps"
echo -e "usernew : untuk membuat akun baru"
echo -e "userlist : untuk melihat daftar akun beserta masa aktifnya"
echo -e "userlimit <limit> : untuk kill akun yang login lebih dari <limit>. Cth: userlimit 1"
echo -e "userlogin  : untuk melihat user yang sedang login"
echo -e "userdelete  : untuk menghapus user"
echo -e "trial : untuk membuat akun trial selama 1 hari"
echo -e "renew : untuk memperpanjang masa aktif akun"
echo -e "info : untuk melihat ulang informasi ini"
